### PR TITLE
Add importmap

### PR DESCRIPTION
**Pull request by felixclack**
The importmap-rails gem is installed in the project but not setup for
use yet.

This is a tool that allows us to import JS dependencies into the project
without needing to use Webpacker.

To add a dependency in the future, run:

```bash
  bin/importmap pin react
```

### CODE REVIEW

**Review by tvararu — APPROVED** [review]
Making a mental note to make sure HTTP/2 is setup correctly, as `importmap` relies on this to get good performance.

**Comment by tvararu** [comment]
Another thought: this context is ADR worthy.

**Comment by felixclack** [comment]
Do you want me to add the ADR in this PR too?

**Comment by tvararu** [comment]
@felixclack no need, we can write it separately, ship this :shipit:

**Pull request merged**
